name: Execute Python Script on Master Push

on:
 #schedule:
    #- cron: '0 0 * * *' # Cette expression CRON déclenche l'exécution tous les jours à minuit
 workflow_dispatch: 

jobs:
  execute_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from swaggyP36000/TrollStore-IPAs
        uses: actions/checkout@v4
        with:
          repository: swaggyP36000/TrollStore-IPAs # Repository B
          path: ipa # Chemin où cloner le dépôt B

      - name: Checkout code from here
        uses: actions/checkout@v4
        with:
          path: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Execute Python script
        run: python ./main/newerVersionApp.py

      - name: List directories
        run: |
          echo "Directories present next to the script:"
          ls
          echo "main echo"
          ls ./main

      - name: Check if file is modified and push changes
        run: |
          cd ./main
          if [[ $(git status --porcelain) ]]; then
              echo "File has been modified"
              git config user.email "actions@github.com"
              git config user.name "GitHub Actions"
              git add scarlet_apps.json
              git commit -m "Update scarlet_apps.json"
              git push origin main
          else
              echo "No changes to commit"
          fi
